### PR TITLE
Fix undeclared javascript variables

### LINKED ISSUE #494: Angular Errors on New Mailing with v2.9.1645644008 and Civi Core 5.46.2
I'm not sure what the root cause is, but whenever we create a New Mailing using the latest Mosaico release and latest Civi core release, we see the following console errors. We cannot select a Group in the Recipients field, it just hangs (spinning wheel) and gives additional console errors. This happens in both Mosaico and Traditional mailings when the Mosaico extension is enabled. I'm guessing there is some incompatibility between the extension and maybe Civi 5.46.2, but not sure. I've cleared caches, cleared the dyn folder, etc, but we still see the errors.

If I disable the Mosaico extension, I can create new traditional mailings without any issues; groups for recipients come up, etc.

This is the first error (on New Mailing page load):
```
Error: [$interpolate:interr] [http://errors.angularjs.org/1.8.2/$interpolate/interr?p0=%7B…inActionLabel)%7D%7D&p1=TypeError%3A%20text%20is%20undefined](http://errors.angularjs.org/1.8.2/$interpolate/interr?p0=%7B%7Bts(mainActionLabel)%7D%7D&p1=TypeError%3A%20text%20is%20undefined)
    Angular 8
[angular.js:15697:15](https://xxx/sites/all/modules/civicrm/bower_components/angular/angular.js)
    Angular 27
    jQuery 7
    api3 crm.ajax.js:118
    Angular 16
    jQuery 7
    api3 crm.ajax.js:118
    Angular 22
    jQuery 5
```

This is the second error (on page load):
```
ReferenceError: assignment to undeclared variable date
    link Angular
    jQuery 6
[angular.js:15697:15](https://xxx/sites/all/modules/civicrm/bower_components/angular/angular.js)
    Angular 14
    jQuery 7
    api3 crm.ajax.js:118
    Angular 16
    jQuery 7
    api3 crm.ajax.js:118
    Angular 22
    jQuery 5
```
And this is the error we get when we click in the Recipients box to pick a group:
```
Uncaught ReferenceError: assignment to undeclared variable results
    results Angular
    success select2.min.js:30
    jQuery 7
    api3 crm.ajax.js:118
    transport Angular
    i select2.min.js:32
    setTimeout handler*C/< select2.min.js:29
    updateResults select2.min.js:110
    opening select2.min.js:180
    open select2.min.js:87
    initContainer select2.min.js:178
    bind select2.min.js:56
    jQuery 8
    initContainer select2.min.js:178
    init select2.min.js:57
    select2 select2.min.js:206
    jQuery 2
    select2 select2.min.js:206
    Angular 10
[angular-modules.038920480d3a401d51d63297f33ab985.js:18003:29](https://xxx/sites/default/files/civicrm/persist/contribute/dyn/angular-modules.038920480d3a401d51d63297f33ab985.js?r830i8)
    results Angular
    success select2.min.js:30
    jQuery 7
    api3 crm.ajax.js:118
    transport Angular
    i select2.min.js:32
    (Async: setTimeout handler)
    C select2.min.js:29
    updateResults select2.min.js:110
    opening select2.min.js:180
    open select2.min.js:87
    initContainer select2.min.js:178
    bind select2.min.js:56
    jQuery 8
    initContainer select2.min.js:178
    init select2.min.js:57
    select2 select2.min.js:206
    jQuery 2
    select2 select2.min.js:206
    Angular 10
```

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/494

Before
----------------------------------------
Javascript errors caused some functionality to break, notably the Mosaico *Recipients* widget.

After
----------------------------------------
All better.

Technical Details
----------------------------------------
These variables need to be declared with the `var` keyword, or it crashes some browsers.

@MegaphoneJon noted that you have to disable debug mode to see the error manifest. It probably depends on your browser too. My theory about that is that in debug mode, each js file is served separately, and these files do not include the `"use strict";` directive, but without debug mode the files all get cobbled together into one big js file, so if one of those said "use strict";` it would affect how the code in this file is treated.

### CODE REVIEW

File: ang/crmMailing/Templates.js [hunk 1]
```diff
@@ -98,7 +98,7 @@
                       results.text = ts('Message Templates');
                     }
 
-                    more = data.more_results;
+                    var more = data.more_results;
 
                     if (more && !data.more_results) {
```
Comment (colemanw) [inline ang/crmMailing/Templates.js:103]: Maybe out-of-scope for this PR, but I just did a double take at the logic of these 2 lines. What the :hankey:???
:laughing:

**Comment by seamuslee001** [comment]
This seems fine to me

File: ang/crmMailing/Templates.js (hunk 1 above)
Comment (colemanw) [reply ang/crmMailing/Templates.js:103]: This fixes it: https://github.com/civicrm/civicrm-core/pull/23188
